name: Call Update commit_sha.txt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  call-update-commit-sha:
    uses: ./.github/workflows/commit_sha.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
